### ISSUE TITLE
Github-actions integrated regression testing suite using extended model-viewer fidelity tests

### ISSUE THREAD

**Issue by bhouston** [gkjohnson/three-gpu-pathtracer#186]
**Is your feature request related to a problem? Please describe.**

It would save a lot of time and make it easier for others to contribute if we were to make a regression testing suite that could be run both (1) locally and (2) triggered via GitHub-actions.  This regression testing suite would render out a sequence of sample scenes and the compare their screenshots with reference screenshots and complain if there is a difference.  It would also save out those new screenshots somewhere so one could inspect them individually.

**Describe the solution you'd like**

It is likely easiest to adapt the model-viewer fidelity testing suite such that we can use its models, and probably add a few, and then use that for this purpose.

It would be nice that on each PR, we can go see a set of screenshots of the various reference scenes and know that they are decent.

**Comment by gkjohnson** [comment]
**TODO**
- [ ] Add query parameters to indicate hiding the GUI and other text
- [ ] Scale the puppeteer window based on the scenario dimensions
- [ ] Broadcast event and stop rendering when a certain number of samples have been taken (based on query param)
- [ ] Save the images to a predetermined folder

**Comment by gkjohnson** [comment]
Added an `npm run diff-screenshots` command and uploaded "goldens" to the "screenshots" branch so we don't bloat the main branch with image commits constantly. Closing in favor of #220 to handle integration with Github Actions if it ever becomes possible
