### ISSUE TITLE
Remaining fidelity / sampling issues

### ISSUE THREAD

**Issue by gkjohnson** [gkjohnson/three-gpu-pathtracer#210]
- [ ] Incorect transmission support (#66)
- [ ] Missing volume support (#66)
- [ ] Diffuse surfaces look dark
- [ ] Rough metal surfaces look too bright (#76)
- [x] Missing clearcoat support (#168)
- [ ] Missing sheen support (#167)
- [ ] Missing iridescence support (#96)

**Comment by bhouston** [comment]
You have taken this renderer so far so fast.  It is incredibly impressive.

The highest priority are the glaring differences with sheen and tangents (it is likely these two lines: https://github.com/mrdoob/three.js/blob/dev/src/renderers/shaders/ShaderChunk/normalmap_pars_fragment.glsl.js#L35) I would suggest.  The furnace test is hard and beyond what you have done the payoff isn't huge.

BTW because I am lazy and I would prefer to keep the internals of the renderer as simple as possible, I would for both "interleaved geometry support" and "flat normals", just have a pre-processing step that converts them to standard non-interleaved geometry (the opposite of this function: https://github.com/threeify/threeify/blob/master/src/lib/geometry/Geometry.Functions.ts#L28) and with proper vertex-normals for flat surfaces so I do not have to make exceptions in the engine.  People could run that immediately after loading a glTF.  Basically a data normalization step.  Otherwise it would skip them and warn that the geometry needs to be normalized or something like that.

**Comment by gkjohnson** [comment]
Thanks!

> The highest priority are the glaring differences with sheen and tangents

I'm not exactly sure why the tangents aren't working as expected. They're required to be generated ahead of time using MikkT or already present in the model so I'm not sure if that section on shader-generated tangents is relevant there.

This line from the spec seems to describe what I'm already doing - but I'll have to dig in more:

> The bitangent vectors MUST be computed by taking the cross product of the normal and tangent XYZ vectors and multiplying it against the W component of the tangent: bitangent = cross(normal.xyz, tangent.xyz) * tangent.w.

https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html

--

> BTW because I am lazy and I would prefer to keep the internals of the renderer as simple as possible, I would for both "interleaved geometry support" and "flat normals", just have a pre-processing step that converts them to standard non-interleaved geometry (the opposite of this function

Agreed on keeping things simple where possible. The flat shading flag really just required [these two lines](https://github.com/gkjohnson/three-gpu-pathtracer/blob/2fe575a862224c648866c1624f411dc5e40053ec/src/materials/PhysicalPathTracingMaterial.js#L642-L649), though, so it's pretty simple. Interleaved buffer geometry is an issue because it can't be merged so a prepocessing step would be the simplest solution in that case.

**Comment by bhouston** [comment]
I believe the issue is that the faces are flipped somehow and you need to invert the tangent space.  I had another PR here to Three.js to replicate this behavior - just try it, I bet it works:

https://github.com/mrdoob/three.js/pull/10694

**Comment by gkjohnson** [comment]
I took a little bit of a deeper look over lunch and I actually think the tangents are being handled correctly. The way normals maps are used is just not well suited to being tested in a path tracer, though.

If you look from above you can see the knobs on the right side are all flat and lighting is affected only by a normal map:

<img width="382" alt="image" src="https://user-images.githubusercontent.com/734200/210700289-99dd7041-7c58-4372-afed-b0a1e50a2767.png">

So what happens at the extreme edges of the dome normals is that the ray glances off the side and barely changes direction - resulting in the subsequent ray facing "underneath" the geometry surface. Right now this is just modeled as the ray being absorbed and causes the black ring on the edge:

<img width="311" alt="image" src="https://user-images.githubusercontent.com/734200/210700498-8a3979b7-a536-4cff-a951-3062b7a1bd64.png">

If we look at the normals themselves, though, we can see that they all look consistent:

<img width="677" alt="image" src="https://user-images.githubusercontent.com/734200/210700550-f8f89743-b640-4e89-8b2e-8c8158a02663.png">

--

The remaining issue relating to tangents, though, is that the "khronos-NormalTangentTest" seems to break when when generating tangents for the model using MikkTSpace.

<img width="546" alt="image" src="https://user-images.githubusercontent.com/734200/210701437-49ede7c0-6a80-4ffa-bedf-1162a08ef530.png">

This is the case without the path tracer, as well (three.js rasterized render):

<img width="569" alt="image" src="https://user-images.githubusercontent.com/734200/210701626-dbd25a00-b1ff-4e31-be67-aeb0fe8219b6.png">

cc @donmccurdy - sorry for the contextless ping. But do you have any thoughts on why generating MikkTSpace tangents would break the "khronos-NormalTangentTest" glTF test model?

**Comment by bhouston** [comment]
Ah, interesting.  I was only referring to the khronos-NormalTangentTest results.  I am pretty sure the reason why normals break in Three.js MikkTSpace is because that PR of mine was never merged in. :). https://github.com/mrdoob/three.js/pull/10694

**Comment by donmccurdy** [comment]
The NormalTangentTest example does not break in the three.js rasterizer with MikkTSpace tangents for me. Maybe we're doing something different here? I tested by loading in https://gltf.report and running the following in the _Script_ tab. The _Metadata_ tab shows the TANGENTS attribute is present as expected.

```javascript
import { tangents, unweld } from '@gltf-transform/functions';
import { generateTangents } from 'mikktspace';

await document.transform(
	unweld(),
	tangents({generateTangents})
);
```


![Screenshot 2023-01-05 at 9 06 48 AM](https://user-images.githubusercontent.com/1848368/210798834-45011797-6b80-47a4-bb8f-948dd842da7d.png)

**Comment by gkjohnson** [comment]
@donmccurdy 
> The NormalTangentTest example does not break in the three.js rasterizer with MikkTSpace tangents for me. Maybe we're doing something different here

I'm not sure how gltf report or those scripts work but something different must be happening. Here's a minimum repro case using the built-in three.js MikkTSpace utility:
https://jsfiddle.net/kpj76ob0/2/
